### ISSUE TITLE
No instructions, no tests, no way to move forward

### ISSUE THREAD

**Issue by LSleutsky** [learn-co-curriculum/sinatra-yield-readme#13]
Not sure the point of this, and why this is a lab and not a README. There is no instructions on what to do or tests to run, so there is no way to move forward. What is it that needs to be done here?

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by joshuabamboo** [comment]
++ @LSleutsky's issue. It's formatted like a lab on Learn but on github it's formatted like a readme with no tests. I think this makes sense as a codealong. @PeterBell

**Comment by AnnJohn** [comment]
changed to a readme. thanks.
