### ISSUE TITLE
What do we do?

### ISSUE THREAD

**Issue by rogerprz** [learn-co-curriculum/sinatra-yield-readme#17]
The lab makes us fork and push, but it doesn't tell us what to do or make a comment or anything.
Maybe it's supposed to be just a read me?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials so it will function as a normal readme and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
