### ISSUE TITLE
404

### ISSUE THREAD

**Issue by LindaHaviv** [learn-co-curriculum/sinatra-yield-readme#2]
this lab cannot be viewed on github

**Comment by AnnJohn** [comment]
thanks @LindaHaviv for now if you want to view it, you can on https://github.com/learn-co-curriculum/sinatra-yield-readme. since it's not a lab, there shouldn't be anything you need to fork, clone, and work on and submit. but please let us know otherwise if that's the case.

**Comment by LindaHaviv** [comment]
Thank you, Anna!!! I am now able to access it. The only thing is Learn
doesn't recognize that you forked it etc. As long as it's not a lab that
works for me.. although I know how obsessed by class is over getting
greenlights hahahaha. Thank you for your help!

**Comment by AnnJohn** [comment]
Should be fixed now. Thanks!
