### ISSUE TITLE
is the final html supposed to have the index.erb information inside of it?

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/sinatra-yield-readme#7]
just looking at it and the only thing that changed was the fact that there's now a line space between the container tag and the i love cats p which was in the previous html. from what i understood the code from index.erb should be replacing the yield statement, it may be a misunderstanding on my part but that's what i understood from it.

**Comment by AnnJohn** [comment]
thanks @pajamaw. We'll look into this but to immediately resolve the issue, please use the Ask a Question tool in Learn and someone will help you out right away to clarify any concepts.

**Comment by victhevenot** [comment]
Hi @pajamaw thanks so much for pointing this out!
